=== s-shimko/java_aqa_speq/resources/rent_units_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/rent_units_schema" xmlns:tns="http://www.example.org/rent_units_schema"
	elementFormDefault="qualified">

	<xs:element name="station">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="equipment" type="tns:EquipmentType"
					maxOccurs="unbounded" />
				<xs:element name="accessory" type="tns:AccessoryType"
					maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:int" />
		</xs:complexType>
	</xs:element>

	<xs:complexType name="EquipmentType">
		<xs:sequence>
			<xs:element name="type" type="xs:string" />
			<xs:element name="title" type="xs:string" />
			<xs:element name="hour_rate" type="xs:double" />
			<xs:element name="category" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" />
	</xs:complexType>

	<xs:complexType name="AccessoryType">
		<xs:complexContent>
			<xs:extension base="tns:EquipmentType">
				<xs:sequence>
					<xs:element name="belong_to" type="xs:string" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

</xs:schema>

=== s-shimko/java_aqa_speq/resources/rent_units.xml
<?xml version="1.0" encoding="UTF-8"?>
<station xmlns="http://www.example.org/rent_units_schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/rent_units_schema rent_units_schema.xsd">

	<equipment id="1">
		<type>Equipment</type>
		<title>Bike</title>
		<hour_rate>2.3</hour_rate>
		<category>Summer</category>
	</equipment>
	<equipment id="2">
		<type>Equipment</type>
		<title>Car</title>
		<hour_rate>2.2</hour_rate>
		<category>Demi</category>
	</equipment>
	<equipment id="3">
		<type>Equipment</type>
		<title>Snowboard</title>
		<hour_rate>2.1</hour_rate>
		<category>Winter</category>
	</equipment>
	<accessory id="1">
		<type>accessory</type>
		<title>Helmet</title>
		<hour_rate>0.3</hour_rate>
		<category>Winter</category>
		<belong_to>Snowboard</belong_to>
	</accessory>
	<accessory id="2">
		<type>accessory</type>
		<title>Carrrier</title>
		<hour_rate>1.3</hour_rate>
		<category>Summer</category>
		<belong_to>Bike</belong_to>
	</accessory>
</station>
