=== s-shimko/java_aqa_speq/resources/station_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/station_schema" xmlns:tns="http://www.example.org/station_schema"
	elementFormDefault="qualified">

	<xs:element name="station">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="equipment" type="tns:EquipmentType"
					maxOccurs="unbounded" />
				<xs:element name="super-equipment" type="tns:SuperEquipmentType"
					maxOccurs="5" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:int">
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="SuperEquipmentType">
		<xs:complexContent>
			<xs:extension base="tns:EquipmentType">
				<xs:sequence>
					<xs:element name="accessories" type="tns:AccessoriesType"
						minOccurs="1" maxOccurs="2" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="AccessoriesType">
		<xs:choice>
			<xs:element name="accessorie" type="xs:string" />
			<xs:element name="protection" type="xs:string" />
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="EquipmentType">
		<xs:sequence>
			<xs:element name="title" type="xs:string" />
			<xs:element name="hour-rate" type="xs:double" />
			<xs:element name="category" type="xs:string" />
			<xs:element name="back-date">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[0-3]{1}[0-9]{1}-[0,1]{1}[0-9]{1}-[0-9]{4}"></xs:pattern>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>

		<xs:attribute name="id" type="xs:int" />
	</xs:complexType>
</xs:schema>

=== s-shimko/java_aqa_speq/resources/rent_station.xml
c<?xml version="1.0" encoding="UTF-8"?>

<station xmlns="http://www.example.org/station_schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/station_schema station_schema.xsd">
	<equipment id="1">
		<title>Snowboard</title>
		<hour-rate>10.2</hour-rate>
		<category>Winter</category>
		<back-date>24-11-2017</back-date>
	</equipment>
	<equipment id="2">
		<title>Bike</title>
		<hour-rate>9.5</hour-rate>
		<category>Summer</category>
		<back-date>24-11-2017</back-date>
	</equipment>
	<equipment id="3">
		<title>Car</title>
		<hour-rate>9.5</hour-rate>
		<category>Demi</category>
		<back-date>24-11-2017</back-date>
	</equipment>

	<super-equipment id="1">
		<title>Snowboard</title>
		<hour-rate>3.2</hour-rate>
		<category>Winter</category>
		<back-date>24-11-2017</back-date>
		<accessories>
			<accessorie>Helmet</accessorie>
		</accessories>
	</super-equipment>
	<super-equipment id="2">
		<title>Bike</title>
		<hour-rate>2.2</hour-rate>
		<category>Summer</category>
		<back-date>24-11-2017</back-date>
		<accessories>
			<accessorie>Carrier</accessorie>
		</accessories>
	</super-equipment>
</station>
